
spring:
  application:
    name: security
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test


jwt:
  secret: mySecretKey123qwertyuixjkdajfjhdfdjkasdbjasjkdl
  expiry: 3600000


